import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Carousel from "@/components/Carousel/Carousel";
import { useMediaQuery } from "@mui/material";
import carouselDesktopImage from "../public/carousel-desktop-image.png"
import carouselMobileImage from "../public/carousel-mobile-image.png"


export default function Home() {
  const isDesktop = useMediaQuery("(min-width:768px)");

  const items = [{
    img: isDesktop ? carouselDesktopImage : carouselMobileImage,
    text1: "Olá o que você está buscando?",
    text2: "Criar ou migrar seu e-commerce?"
  }, 
  {
    img: isDesktop ? carouselDesktopImage : carouselMobileImage,
    text1: "Olá o que você está buscando?",
    text2: "Criar ou migrar seu e-commerce?"
  }, 
  {
    img: isDesktop ? carouselDesktopImage : carouselMobileImage,
    text1: "Olá o que você está buscando?",
    text2: "Criar ou migrar seu e-commerce?"
  }, 
]

  return (
    <>
      <Head>
        <title>Corebiz E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Carousel items={items}/>
      </main>
    </>
  );
}
